### ISSUE TITLE
Can't compile with Rust 1.17

### ISSUE THREAD

**Issue by e-oz** [ctz/rustls#57] opened 2017-03-16 20:38 UTC
The attribute `export_macro` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)
 --> /.cargo/registry/src/github.com/rustls-0.5.6/src/msgs/macros.rs:3:1
  |
3 | #[export_macro]
  | ^^^^^^^^^^^^^^^

error: aborting due to previous error

**Comment by e-oz** [comment] 2017-03-16 20:39
therefore can't compile Hyper

**Comment by ctz** [comment] 2017-03-16 20:59
Sorry for the inconvenience. This is a dupe of #56 and should be fixed if you take 0.5.8

**Closed by ctz** 2017-03-16 20:59 UTC

**Comment by e-oz** [comment] 2017-03-16 21:02
@ctz thank you very much for so operative fix.
